In [1]:
%cd ..

import pandas as pd
pd.set_option('display.max_columns', None)

from scripts.utils import *

/run/media/nazif/2F946E411BA61D49/thesis

In [2]:
assembly = import_pyensembl(37)

INFO:pyensembl.sequence_data:Loaded sequence dictionary from /run/media/nazif/2F946E411BA61D49/data/pyensembl/GRCh37/ensembl75/Homo_sapiens.GRCh37.75.cdna.all.fa.gz.pickle
INFO:pyensembl.sequence_data:Loaded sequence dictionary from /run/media/nazif/2F946E411BA61D49/data/pyensembl/GRCh37/ensembl75/Homo_sapiens.GRCh37.75.ncrna.fa.gz.pickle
INFO:pyensembl.sequence_data:Loaded sequence dictionary from /run/media/nazif/2F946E411BA61D49/data/pyensembl/GRCh37/ensembl75/Homo_sapiens.GRCh37.75.pep.all.fa.gz.pickle

In [4]:
df = pd.read_csv("results/7_results_0_50.csv")
df.head()

,id,mrna_start,mrna_end,mrna_sequence,mirna_accession,mirna_start,mirna_end,mirna_sequence,mrna_dot_bracket_5to3,mirna_dot_bracket_5to3,pred_energy,is_mutated
0,1_809687_G_C_MIMAT0000062,5,26,ATATCAGCAATATCAGGATGCCACGGCTGAGGAGGAGGAGTTTGAG...,MIMAT0000062,0,17,TGAGGTAGTAGGTTGTATAGTT,.(((((.......((((.((.,)).))))....))))).,-6.9,0
1,1_809687_G_C_MIMAT0004481,29,54,ATATCAGCAATATCAGGATGCCACGGCTGAGGAGGAGGAGTTTGAG...,MIMAT0004481,0,21,CTATACAATCTACTGTCTTTC,.((((((..(((..((...(((((.,.)))))..)).))).)))))),-9.5,0
2,1_809687_G_C_MIMAT0010195,32,61,ATATCAGCAATATCAGGATGCCACGGCTGAGGAGGAGGAGTTTGAG...,MIMAT0010195,0,22,CTGTACAGCCTCCTAGCTTTCC,.(((.(((((..(((((...((((.(.((,)).).))))))))))))))))),-16.8,0
3,1_809687_G_C_MIMAT0000063,15,57,ATATCAGCAATATCAGGATGCCACGGCTGAGGAGGAGGAGTTTGAG...,MIMAT0000063,4,22,TGAGGTAGTAGGTTGTGTGGTT,.(((..(((((((.......................(((((.,.))))))))))))..))),-8.8,0
4,1_809687_G_C_MIMAT0004482,29,54,ATATCAGCAATATCAGGATGCCACGGCTGAGGAGGAGGAGTTTGAG...,MIMAT0004482,0,22,CTATACAACCTACTGCCTTCCC,.(((((.(.(((...(((.(((((.,.)))))..)))))).)))))).,-15.0,0

In [5]:
df = generate_positions_from_id(df)
df = generate_alignment_string_from_dot_bracket(df)
df = generate_match_count_columns(df)
df = generate_ta_sps_columns(df)
df = generate_mre_sequence_for_vcf(df)
df = generate_important_sites(df)
df = generate_mirna_conservation_column(df)
df = generate_seed_type_columns(df)
df = generate_mre_au_content_column(df)
df = generate_au_content_column_for_vcf(df)


df.head()

,id,mrna_start,mrna_end,mrna_sequence,mirna_accession,mirna_start,mirna_end,mirna_sequence,mrna_dot_bracket_5to3,mirna_dot_bracket_5to3,pred_energy,is_mutated,chr,start_coordinate,end_coordinate,alignment_string,pred_num_basepairs,pred_seed_basepairs,ta_log10,sps_mean,mre_end,mre_start,mre_region,anchor_a,6mer_seed,match_8,6mer_seed_1_mismatch,compensatory_site,supplementary_site,supplementary_site_2,empty_seed,9_consecutive_match_anywhere,mirna_conservation,seed_8mer,seed_7mer_a1,seed_7mer_m8,seed_compensatory,seed_clash_2,seed_clash_3,seed_clash_4,seed_clash_5,mre_au_content,au_content_sequence,local_au_content
0,1_809687_G_C_MIMAT0000062,5,26,ATATCAGCAATATCAGGATGCCACGGCTGAGGAGGAGGAGTTTGAG...,MIMAT0000062,0,17,TGAGGTAGTAGGTTGTATAGTT,.(((((.......((((.((.,)).))))....))))).,-6.9,0,1,809662,809683,110111100001111100000,11,5,3.393,-8.180,26,4,CAGCAATATCAGGATGCCACGG,0,0,0,1,0,1,0,0,0,2.0,0,0,0,0,0,0,0,1,0.454545,GCAACATGAACGACCTGGTGTCTGAATATCAGCAATATCAGGATGC...,0.500000
1,1_809687_G_C_MIMAT0004481,29,54,ATATCAGCAATATCAGGATGCCACGGCTGAGGAGGAGGAGTTTGAG...,MIMAT0004481,0,21,CTATACAATCTACTGTCTTTC,.((((((..(((..((...(((((.,.)))))..)).))).)))))),-9.5,0,1,809686,809711,011111001101110111111,16,5,3.716,-3.710,54,33,GGAGGAGTTTGAGGAGTATGC,0,0,0,1,0,0,1,0,0,-1.0,0,0,0,0,0,0,0,1,0.476190,AATATCAGCAATATCAGGATGCCACGGCTGAGGAGGAGGAGTTTGA...,0.523256
2,1_809687_G_C_MIMAT0010195,32,61,ATATCAGCAATATCAGGATGCCACGGCTGAGGAGGAGGAGTTTGAG...,MIMAT0010195,0,22,CTGTACAGCCTCCTAGCTTTCC,.(((.(((((..(((((...((((.(.((,)).).))))))))))))))))),-16.8,0,1,809689,809718,1101011111111111111111,20,4,3.549,-6.275,61,39,GTTTGAGGAGTATGCTGAGGAG,0,0,1,0,1,1,1,0,1,-1.0,0,0,0,0,0,0,0,1,0.500000,ATCAGCAATATCAGGATGCCACGGCTGAGGAGGAGGAGTTTGAGGA...,0.511111
3,1_809687_G_C_MIMAT0000063,15,57,ATATCAGCAATATCAGGATGCCACGGCTGAGGAGGAGGAGTTTGAG...,MIMAT0000063,4,22,TGAGGTAGTAGGTTGTGTGGTT,.(((..(((((((.......................(((((.,.))))))))))))..))),-8.8,0,1,809672,809714,0000011111111111100111,15,2,3.393,-8.180,61,39,GTTTGAGGAGTATGCTGAGGAG,0,0,1,0,1,1,0,0,1,2.0,0,0,0,0,0,0,0,1,0.500000,CGACCTGGTGTCTGAATATCAGCAATATCAGGATGCCACGGCTGAG...,0.504854
4,1_809687_G_C_MIMAT0004482,29,54,ATATCAGCAATATCAGGATGCCACGGCTGAGGAGGAGGAGTTTGAG...,MIMAT0004482,0,22,CTATACAACCTACTGCCTTCCC,.(((((.(.(((...(((.(((((.,.)))))..)))))).)))))).,-15.0,0,1,809686,809711,0111110011111101111110,17,5,3.716,-3.710,54,32,AGGAGGAGTTTGAGGAGTATGC,0,0,0,1,0,0,1,0,0,-1.0,0,0,0,0,0,0,0,1,0.500000,AATATCAGCAATATCAGGATGCCACGGCTGAGGAGGAGGAGTTTGA...,0.523256

In [6]:
df.to_csv("results/8_adding_feature_cols_0_50.csv", index=False)