In [1]:
import pandas as pd

# notes


cell line = HEK293T

In [13]:
df = pd.read_csv("../../data/mirbind eclip/rep1.tsv", sep="\t")

print(df.columns)

Index(['chr.g', 'start.g', 'end.g', 'flag.g', 'strand.g', 'gene_name',
       'gene_biotype', 'seq.g', 'noncodingRNA_real_seq', 'noncodingRNA',
       'noncoding_simplified', 'noncodingRNA_type', 'miRNA_fam', 'forward_dir',
       'Ndups', 'Nunique', 'dups_perc', 'repeatmasker', 'repeat_fam',
       'feature', 'vars', 'yrna', 'smallRNA_nomm', 'mrna_length', 'cov',
       'Nreads', 'mrna_aln', 'mrna_aln2', 'mrna_aln5', 'mrna_aln10',
       'mrna_aln20', 'A_perc', 'C_perc', 'G_perc', 'T_perc', 'mfe_struct',
       'mfe', 'ene', 'noncoding_mirna_annot', 'noncoding_trna_annot',
       'noncoding_rrna_annot', 'noncoding_snorna_annot',
       'noncoding_yrna_annot', 'noncoding_vaultrna_annot', 'noncoding_unique',
       'noncodingRNA_seq'],
      dtype='object')

# dropping irrelevant columns & filtering only miRNAs

In [18]:
cols_to_keep = ['chr.g', 'start.g', 'end.g', 'strand.g', 'gene_name', 'seq.g', 'noncodingRNA_real_seq', 'noncoding_simplified', 
                'noncodingRNA_type', 'feature', 'mfe']

df = df[cols_to_keep]

df[df["noncodingRNA_type"] == "miRNA"]

,chr.g,start.g,end.g,strand.g,gene_name,seq.g,noncodingRNA_real_seq,noncoding_simplified,noncodingRNA_type,feature,mfe
0,MT,5994,6033,+,MT-CO1,ACAGCTCTAAGCCTCCTTATTCGAGCCGAGCTGGGCCAGC,TCCGGCTCGAAGGACCA,14_20659958_20660051_-_tRNA-Tyr-GTA-7-1_tRNA,tRNA,exon,-22.6
1,MT,13689,13757,+,MT-ND5,AAACCCCATTAAACGCCTGGCAGCCGGAAGCCTATTCGCAGGATTT...,TTCCGGCTCGAAGGACCA,14_20653099_20653192_-_tRNA-Tyr-GTA-5-3_tRNA,tRNA,exon,-19.9
2,19,12939516,12939562,+,CALR,GTTCACGGTGAAACATGAGCAGAACATCGACTGTGGGGGCGGCTATG,TCCGGCTCGAAGGACCA,14_20659958_20660051_-_tRNA-Tyr-GTA-7-1_tRNA,tRNA,exon,-15.4
3,1,157122182,157122242,-,ETV3,TTTTTCTCCCCTCAGCCCACTCCTGGTAGCACCTGTCGCCAGCCTG...,TCCGGCTCGAAGGACCA,14_20659958_20660051_-_tRNA-Tyr-GTA-7-1_tRNA,tRNA,three_prime_utr,-27.5
4,9,110256419,110256475,-,TXN,ATCGGTCCTTACAGCCGCTCGTCAGACTCCAGCAGCCAAGATGGTG...,TTCCGGCTCGAAGGACCA,14_20653099_20653192_-_tRNA-Tyr-GTA-5-3_tRNA,tRNA,"exon,five_prime_utr",-25.4

In [20]:
df2 = pd.read_csv("../../data/mirbind eclip/rep2.tsv", sep="\t")
cols_to_keep = ['chr.g', 'start.g', 'end.g', 'strand.g', 'gene_name', 'seq.g', 'noncodingRNA_real_seq', 'noncoding_simplified', 
                'noncodingRNA_type', 'feature', 'mfe']

df2 = df2[cols_to_keep]

df2[df2["noncodingRNA_type"] == "miRNA"]

,chr.g,start.g,end.g,strand.g,gene_name,seq.g,noncodingRNA_real_seq,noncoding_simplified,noncodingRNA_type,feature,mfe
10,X,151408962,151409050,+,VMA21,AGTAATAATAGCAATAGCTAACAACATCTGCACAGCACCTTACAGT...,TAAGGTGCATCTAGTGCAGATAG,hsa-miR-18a-5p,miRNA,three_prime_utr,-30.4
103,16,9039374,9039406,-,NaN,GGACGTGTCTCTCTCTCTCTCTCTCTCTCTCTC,TCTCTCTCTCTCTCTCTCTCA,hsa-miR-6873-3p,miRNA,NaN,-3.9
136,X,151408904,151408992,+,VMA21,TTGTCAGTTATACAGAGTAGTCTTCCTTTTCCCCACGTTCAGTGTA...,TAAGGTGCATCTAGTGCAGATAG,hsa-miR-18a-5p,miRNA,three_prime_utr,-23.9
172,12,110731776,110731868,-,PPP1CC,TTCAGGAGAATGAAATCAGAGGACTGTGCTTAAAGTCTCGTGAAAT...,TTCAAGTAATCCAGGATAGGCT,hsa-miR-26a-5p,miRNA,exon,-39.4
193,MT,10738,10808,+,MT-ND4,TACATAACCTAAACCTACTCCAATGCTAAAACTAATCGTCCCAACA...,TAGGTAGTTTCCTGTTGTTGGG,hsa-miR-196b-5p,miRNA,exon,-21.4
...,...,...,...,...,...,...,...,...,...,...,...
2507,11,66771094,66771181,+,C11orf80,TAAATGTCTTTACCTTCTATTTTTCTGAAAAGGTTGAGGTTATCCA...,TTTAGAGATGAGGTCTTGCT,hsa-miR-1303,miRNA,intron,-20.4
2512,X,140783724,140783778,+,"LINC00632,CDR1",TCAATCCACATCTTCCGGAAAAAATCCAGGTCTTCCAGCCAATATA...,TTTCCGGCTCGCGTGGGTGT,hsa-miR-1180-3p,miRNA,exon,-20.1
2513,17,46031602,46031663,-,KANSL1,ACAGTCCCCAGGCGGAGTGTGAGGACCAGCTGGATGCACAGGAGCG...,TTTCCGGCTCGCGTGGGTGTGT,hsa-miR-1180-3p,miRNA,exon,-31.4
2517,13,99986286,99986369,+,ZIC2,CTTCATGTAACTATAGACTGGAAAAAATGAGCCGTGCCAAAGTCTC...,TTTGGCACTAGCACATTTTTGC,hsa-miR-96-5p,miRNA,three_prime_utr,-23.5
2524,12,69768094,69768156,+,RAB3IP,GTCTGCAGATCTGCTTGGGTGTGTAGTGGAGAGGACCTCACTGTAC...,TTTTGCAAGCTGTTCCTGAAT,hsa-miR-450b-5p,miRNA,intron,-22.0